/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import java.io.File;

public class App {

    public static void main(String[] args) {

        // create new Bitmap
        Bitmap newBitmap = new Bitmap();

        // read image
        newBitmap.readBitmap(new File(args[0]));

        // perform transformation
        if (args[2].equals("invert")) {
            System.out.println(newBitmap.invertImage());
        }

        // write image
        newBitmap.imageToFile(new File(args[1]));
    }
}
